//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int SECUENCIAL { get; set; }
        public int SECUENCIALPRESTAMO { get; set; }
        public decimal VALORPAGO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal SALDOPRESTAMO { get; set; }
    
        public virtual PRESTAMO PRESTAMO { get; set; }
    }
}
