DECLARE db_cursor CURSOR FOR (SELECT SECUENCIAL, VALOR FROM NUMEROS); DECLARE @SECUENCIAL INT;DECLARE @VALOR INT;OPEN db_cursor;FETCH NEXT FROM db_cursor INTO @SECUENCIAL, @VALOR;	WHILE @@FETCH_STATUS = 0  		BEGIN  
			IF @VALOR % 3 = 0
				BEGIN
					UPDATE NUMEROS SET VALOR = @VALOR*100 WHERE SECUENCIAL = @SECUENCIAL
				END
		FETCH NEXT FROM db_cursor INTO @SECUENCIAL, @VALOR;		END;CLOSE db_cursor;DEALLOCATE db_cursor;

