--Punto # 5.1 --
--ACTUALIZACION CAMPO SECUENCIAL EN SQL--
--SE ELIMINA EL CAMPO SECUENCIAL--
ALTER TABLE PAGO DROP COLUMN SECUENCIAL 
ALTER TABLE dbo.PAGO
   ADD SECUENCIAL INT IDENTITY(1,1) CONSTRAINT PK_PAGO PRIMARY KEY  
	 
--Punto # 5.2--
-- ACTUALIZAR CAMPO VALORPAGO A TIPO ENTERO --
ALTER TABLE PAGO ALTER COLUMN VALORPAGO INT 

select * from TIPOIDENTIFICACION
