-- EXEC ListarPagos @PARAMETRO1 = 0  --LLAMADO
CREATE PROCEDURE ListarPagos(
	@PARAMETRO1 VARCHAR(15))
AS
BEGIN
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

IF @PARAMETRO1 = '0'
	SELECT 
		P.IDENTIFICACION, 
		CONCAT(P.PRIMERNOMBRE,P.SEGUNDONOMBRE,P.PRIMERAPELLIDO,P.SEGUNDOAPELLIDO) AS NOMBRECOMPLETO, 
		PG.SECUENCIALPRESTAMO, 
		PG.FECHA,
		SUM(PG.VALORPAGO) AS PAGOALAFECHA
	FROM 
		PAGO PG		
		INNER JOIN PERSONA P ON PG.SECUENCIAL = P.SECUENCIAL
	GROUP BY
		P.IDENTIFICACION, P.PRIMERNOMBRE,P.SEGUNDONOMBRE,P.PRIMERAPELLIDO,P.SEGUNDOAPELLIDO, PG.SECUENCIALPRESTAMO, PG.FECHA
ELSE
	SELECT 
		P.IDENTIFICACION, 
		CONCAT(P.PRIMERNOMBRE,P.SEGUNDONOMBRE,P.PRIMERAPELLIDO,P.SEGUNDOAPELLIDO) AS NOMBRECOMPLETO, 
		PG.SECUENCIALPRESTAMO, 
		PG.FECHA,
		SUM(PG.VALORPAGO) AS PAGOALAFECHA
	FROM 
		PAGO PG		
		INNER JOIN PERSONA P ON PG.SECUENCIAL = P.SECUENCIAL
	WHERE
		P.IDENTIFICACION = @PARAMETRO1
	GROUP BY
		P.IDENTIFICACION, P.PRIMERNOMBRE,P.SEGUNDONOMBRE,P.PRIMERAPELLIDO,P.SEGUNDOAPELLIDO, PG.SECUENCIALPRESTAMO, PG.FECHA
	
END
GO
