DROP TABLE IF EXISTS #MULTIPLOS
CREATE TABLE #MULTIPLOS(
	SECUENCIAL INT,
	VALOR INT
);

DECLARE db_cursor CURSOR FOR (SELECT SECUENCIAL, VALOR FROM NUMEROS); 
DECLARE @SECUENCIAL INT;
DECLARE @VALOR INT;
OPEN db_cursor;
FETCH NEXT FROM db_cursor INTO @SECUENCIAL, @VALOR;
WHILE @@FETCH_STATUS = 0  
		BEGIN  
			IF @VALOR % 5 = 0
				BEGIN
					INSERT INTO #MULTIPLOS(SECUENCIAL, VALOR) VALUES(@SECUENCIAL, @VALOR)
				END
	    FETCH NEXT FROM db_cursor INTO @SECUENCIAL, @VALOR;
END;
CLOSE db_cursor;
DEALLOCATE db_cursor;
SELECT * FROM #MULTIPLOS
