-- EXEC ListarPrestamos @PARAMETRO1 = 0  --LLAMADO

CREATE PROCEDURE ListarPrestamos(
	@PARAMETRO1 VARCHAR(15))
AS
BEGIN
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

IF @PARAMETRO1 = '0'
	SELECT
		P.TIPOIDENTIFICACION, P.IDENTIFICACION, CONCAT(P.PRIMERNOMBRE, ' ', P.SEGUNDONOMBRE, ' ', P.PRIMERAPELLIDO,' ',P.SEGUNDOAPELLIDO) AS NOMBRECOMPLETO, PR.SECUENCIAL,PR.MONTO,PR.ESTADO 
	FROM 
		PRESTAMO PR 
			INNER JOIN PERSONA P ON  PR.SECUENCIALPERSONA = P.SECUENCIAL
ELSE
	SELECT
		P.TIPOIDENTIFICACION, P.IDENTIFICACION, CONCAT(P.PRIMERNOMBRE, ' ', P.SEGUNDONOMBRE, ' ', P.PRIMERAPELLIDO,' ',P.SEGUNDOAPELLIDO) AS NOMBRECOMPLETO, PR.SECUENCIAL,PR.MONTO,PR.ESTADO
	FROM 
		PRESTAMO PR 
			INNER JOIN PERSONA P ON  PR.SECUENCIALPERSONA = P.SECUENCIAL
	WHERE
		P.IDENTIFICACION = @PARAMETRO1

END
GO
	